/*  DEVIL - Descent Editor for Vertices, Items and Levels at all
    credits.h - the credits. if you falsify it, devil will format
     your harddisk and let your monitor explode. if you've done some
     work on devil you can put a note inside but better idea is to
     sent me your work so I can do the note inside and your work in
     devil.
    Copyright (C) 1995  Achim Stremplat (ubdb@rzstud1.uni-karlsruhe.de)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program (file COPYING); if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. */
    
char *cred_txt[] = {
 "DEVIL - Version 0.96b2 - Date: 22.03.95",
 "DESCENT Editor for Vertices, Items and Levels at all",
 "-----------------------------------------------------",
 "Copyright (C) 1995 Achim Stremplat.",
 "DEVIL comes with ABSOLUTELY NO WARRANTY.",
 "This is free software, and you are welcome to",
 "redistribute it under certain conditions.",
 "For further information see file 'COPYING'",
 "-----------------------------------------------------",
 "Pfuuah, I hate these copyright notices, but I suppose",
 "I don't want to pay your descent if you'll destroy it",
 "But now the credits:",
 "Super-Duper-Mega and XXXXXXXXXXXXX-thanks must go to",
 "BORIS POSTLER (for the documentation and testing).",
 "-----------------------------------------------------",
 "Normal thanks must go to:",
 "- The guys from Parallax for making a great game.",
 "- Gerrit Jahn for the projecting-idea.",
 "- The people who made GNU-C.",
 "- The Pizza World in Karlsruhe for giving me food.",
 "- The TU-Karlsruhe for granting me access to internet",
 "-----------------------------------------------------",
 "Special thanks must go to:",
 "- Again Gerrit Jahn for destroying my chair.",
 "- Prof. H. for making a strange lecture so I've ",
 "  decided, it makes more sense making this editor.",
 "- Again the guys from Parallax for changing the",
 "  level-file-format from the shareware to the ",
 "  registered version.",
 NULL };
 