/*  DEVIL - Descent Editor for Vertices, Items and Levels at all
    credits.h - the credits. if you falsify it, Devil will format
     your harddisk and let your monitor explode. if you've done some
     work on Devil you can put a note inside but better idea is to
     sent me your work so I can do the note inside and your work in
     Devil.
    Copyright (C) 1995  Achim Stremplat (ubdb@rz.uni-karlsruhe.de)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program (file COPYING); if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. */

#include "version.h"    

const char *cred_txt[] = {
 "DEVIL - Version "VERSION" - Date: "__DATE__" Time: "__TIME__,
 "DESCENT Editor for Vertices,Items and Levels at all",
 "For the latest release try:",
 " http://wwwrzstud.rz.uni-karlsruhe.de/~ubdb/index.html (with source)",
 "--------------------------------------------------------------------------",
 "Devil is sponsored by the German Gamer's Magazin PC Player.",
 "--------------------------------------------------------------------------",
 "Copyright 1995 Achim Stremplat. DEVIL comes with ABSOLUTELY NO WARRANTY.",
 "This is free software, and you are welcome to redistribute it under",
 "certain conditions. For further information see file 'COPYING'",
 "Distribution with commercial or shareware programs is allowed",
 "but requires notification of the author by mail or email.",
 "--------------------------------------------------------------------------",
 "Thanks must go to",
 "- Boris Schneider from PC Player for support.",
 "- The guys from Parallax for making a great",
 "  game&support&my new computer system.",
 "--------------------------------------------------------------------------",
 "If debugging is the procedure to fix bugs in a program,",
 "then programming is the procedure to create bugs.",
 NULL };
