/*  DEVIL - Descent Editor for Vertices, Items and Levels at all
    credits.h - the credits. if you falsify it, devil will format
     your harddisk and let your monitor explode. if you've done some
     work on devil you can put a note inside but better idea is to
     sent me your work so I can do the note inside and your work in
     devil.
    Copyright (C) 1995  Achim Stremplat (ubdb@rz.uni-karlsruhe.de)

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 2 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program (file COPYING); if not, write to the Free Software
    Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA. */
    
char *cred_txt[] = {
 "DEVIL - Version 0.99 - Date: 10.04.95",
 "DESCENT Editor for Vertices,Items and Levels at all",
 "---------------------------------------------------",
 "Copyright (C) 1995 Achim Stremplat.",
 "DEVIL comes with ABSOLUTELY NO WARRANTY.",
 "This is free software, and you are welcome to",
 "redistribute it under certain conditions.",
 "For further information see file 'COPYING'",
 "---------------------------------------------------",
 "Pfuuah, I hate these copyright notices, but I",
 "suppose I don't want to pay your descent if you'll",
 "destroy it.",
 "More than normal thanks must go to",
 "- Boris Postler (for the docs and testing).",
 "- Bob Sip for doing the Borland-C version.",
 "- G.P.Smith for doing the OS/2 version.",
 "- The guys from Parallax for making a great game.",
 "--------------------------------------------------",
 "Normal thanks must go to:",
 "- All the guys reporting bugs, making suggestions.",
 "- All the people who created GNU-C.",
 "- The Pizza World in Karlsruhe.",
 "---------------------------------------------------",
 "Sorry that this version comes a bit late but",
 "always remember Windows 96 - oh sorry 97.",
 NULL };
